"""initial schema

Revision ID: 2c72e5e0e8cd
Revises:
Create Date: 2026-06-25 05:21:02.225708

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c72e5e0e8cd"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "languages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "levels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("is_student", sa.Boolean(), nullable=False),
        sa.Column("is_teacher", sa.Boolean(), nullable=False),
        sa.Column("is_email_verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone_number"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "teacher_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=100), nullable=False),
        sa.Column("headline", sa.String(length=160), nullable=False),
        sa.Column("short_bio", sa.Text(), nullable=False),
        sa.Column("specialization", sa.String(length=200), nullable=True),
        sa.Column("hourly_rate", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("rating", sa.Numeric(precision=2, scale=1), nullable=False),
        sa.Column("reviews_count", sa.Integer(), nullable=False),
        sa.Column("lessons_count", sa.Integer(), nullable=False),
        sa.Column("is_pro", sa.Boolean(), nullable=False),
        sa.Column("available_mornings", sa.Boolean(), nullable=False),
        sa.Column("available_evenings", sa.Boolean(), nullable=False),
        sa.Column("avatar_color", sa.String(length=7), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "class_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("session_type", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("level_label", sa.String(length=20), nullable=False),
        sa.Column("language_code", sa.String(length=10), nullable=False),
        sa.Column("teacher_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["teacher_id"], ["teacher_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_class_sessions_start_time"), "class_sessions", ["start_time"], unique=False
    )
    op.create_table(
        "student_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=100), nullable=False),
        sa.Column("preferred_language", sa.String(length=10), nullable=False),
        sa.Column("current_level_id", sa.Integer(), nullable=True),
        sa.Column("assigned_teacher_id", sa.Integer(), nullable=True),
        sa.Column("profile_completion", sa.Integer(), nullable=False),
        sa.Column("streak_days", sa.Integer(), nullable=False),
        sa.Column("unread_messages", sa.Integer(), nullable=False),
        sa.Column("avatar_color", sa.String(length=7), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_teacher_id"], ["teacher_profiles.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["current_level_id"], ["levels.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "teacher_languages",
        sa.Column("teacher_profile_id", sa.Integer(), nullable=False),
        sa.Column("language_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["language_id"], ["languages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["teacher_profile_id"], ["teacher_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("teacher_profile_id", "language_id"),
    )
    op.create_table(
        "session_students",
        sa.Column("class_session_id", sa.Integer(), nullable=False),
        sa.Column("student_profile_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["class_session_id"], ["class_sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["student_profile_id"], ["student_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("class_session_id", "student_profile_id"),
    )
    op.create_table(
        "teacher_reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("teacher_id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["student_id"], ["student_profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["teacher_id"], ["teacher_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("teacher_reviews")
    op.drop_table("session_students")
    op.drop_table("teacher_languages")
    op.drop_table("student_profiles")
    op.drop_index(op.f("ix_class_sessions_start_time"), table_name="class_sessions")
    op.drop_table("class_sessions")
    op.drop_table("teacher_profiles")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("levels")
    op.drop_table("languages")
    # ### end Alembic commands ###
